---
- name: Set up libvirt, QEMU, and Virt-Manager
  import_playbook: arch_setup-libvirt-qemu.yml

- name: Get Arch Linux cloud image
  import_playbook: get-vm.yml

- name: Import and configure VM
  import_playbook: import-vm.yml
